[workspace]
resolver = "2"
members = [
    "crates/newgc-core",
    "crates/newgc-test-lisp",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/anthropic-experiments/NewGC"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[profile.release]
debug = true
lto = "thin"
